export const FETCH_ORDERS_REQUEST = 'FETCH_ORDERS_REQUEST'
export const FETCH_ORDERS_SUCCESS = 'FETCH_ORDERS_SUCCESS'
export const FETCH_ORDERS_FAILURE = 'FETCH_ORDERS_FAILURE'

export const SAVE_ORDER_REQUEST = 'SAVE_ORDER_REQUEST'
export const SAVE_ORDER_SUCCESS = 'SAVE_ORDER_SUCCESS'
export const SAVE_ORDER_FAILURE = 'SAVE_ORDER_FAILURE'

export const ADD_ORDER = 'ADD_ORDER'
